apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: okd-fs
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  metadataPool:
    replicated:
      size: 3
  dataPools:
    - replicated:
        size: 2
  preserveFilesystemOnDelete: false
  metadataServer:
    activeCount: 1
    activeStandby: true
